In [1]:
# grammar = CFG.fromstring("""
# S -> NP VP
# NP -> DT NN
# VP -> V NP
# DT -> 'the'
# NN -> 'boy' | 'ball'
# V -> 'kicked'
# """)


# parser = ChartParser(grammar)

# for tree in parser.parse(tokens):
#     print(tree)
#     tree.pretty_print()


In [2]:
# applications
# 1) sentiment analysis
# 2) chatbot
# 3) langauge translataion
# 4) word prediction
# 5) stock market prediction
# 6) weather forcasting
# 7) alexa /siri  Speech recognition
# 8) Text generation




In [4]:
# import numpy as np
# import pandas as pd
# from tensorflow.keras.layers import Dense,SimpleRNN
# from tensorflow.keras.models import Sequential

In [ ]:
# many to one

In [5]:
# X= np.array([[1,2,3,4]])
# y=np.array([5])

In [6]:
# input reshape

In [7]:
# CNN >> 1,256,256,3
# RNN >> 1,4,1 

In [11]:
# X.shape

(1, 4)

In [8]:
# X_new=X.reshape((1,4,1))

In [9]:
# X_new

array([[[1],
        [2],
        [3],
        [4]]])

In [10]:
# y

array([5])

In [12]:
# model training

In [14]:
# model=Sequential([
#     SimpleRNN(10,activation='relu',input_shape=(4,1)),
#     Dense(1)
# ])

In [15]:
# model.compile(optimizer='adam',loss='mse')

In [22]:
# model.fit(X_new,y,epochs=400)

Epoch 1/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 7.3107
Epoch 2/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 7.1565
Epoch 3/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - loss: 7.0019
Epoch 4/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - loss: 6.8471
Epoch 5/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 6.6921
Epoch 6/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - loss: 6.5370
Epoch 7/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - loss: 6.3826
Epoch 8/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - loss: 6.2271
Epoch 9/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 166ms/step - loss: 6.0724
Epoch 10/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - loss: 5.9179
Epoch 11/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - loss: 5.7635
Epoch 12/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - loss: 5.6093
Epoch 13/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - loss: 5.4556
Epoch 14/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - loss: 5.3023
Epoch 15/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - loss: 5.1495
Epoch 16/400
1/1 ━

In [23]:
# model.predict(X_new)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step


array([[4.9999986]], dtype=float32)

In [24]:
# a= np.array([[6,7,8,9]])

In [25]:
# a_new=a.reshape((1,4,1))

In [26]:
# model.predict(a_new)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step


array([[10.990681]], dtype=float32)

In [27]:
# case study 1 restaurant reviews predictions
# many to one
# LSTM/GRu

In [1]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, LSTM, GRU, Dense
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np
import pandas as pd




In [2]:
df=pd.read_csv('r_data.tsv',delimiter='\t')

In [3]:
df

,Review,Liked
0,Wow... Loved this place.,1
1,Crust is not good.,0
2,Not tasty and the texture was just nasty.,0
3,Stopped by during the late May bank holiday of...,1
4,The selection on the menu was great and so wer...,1
...,...,...
1386,bad,0
1387,very bad,0
1388,bad food,0
1389,bad space,0


In [4]:
df.shape

(1391, 2)

In [5]:
# data cleaning
df.isnull().sum()

Review    0
Liked     0
dtype: int64

In [6]:
df.dtypes

Review    object
Liked      int64
dtype: object

In [7]:
# ann/cnn >> 
# text ==input

In [8]:
df['Review']

0                                Wow... Loved this place.
1                                      Crust is not good.
2               Not tasty and the texture was just nasty.
3       Stopped by during the late May bank holiday of...
4       The selection on the menu was great and so wer...
                              ...                        
1386                                                  bad
1387                                             very bad
1388                                             bad food
1389                                            bad space
1390                                          bad service
Name: Review, Length: 1391, dtype: object

In [9]:
# Text proprocessing
#lowercase,special characters digit stopwords steming

In [10]:
# NLP >> nltk

In [11]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer
import re # regular Expression


In [12]:
s_list=stopwords.words('english')

In [13]:
s_list.remove('not')

In [14]:
len(s_list)

197

In [15]:
corpus=[]
for i in df['Review']:
    mystr=i.lower() # lowercase
    newstr= re.sub(r'[^A-Za-z\s]','',mystr)# remove special character and digit
    list1=word_tokenize(newstr) # tokenization
    list2=[ i for i in list1 if i not in s_list] # stopwords  remove
    ps=PorterStemmer()
    list3=[ps.stem(i) for i in list2] # stemming
    final=' ' .join(list3)
    corpus.append(final)
   

In [16]:
corpus

['wow love place',
 'crust not good',
 'not tasti textur nasti',
 'stop late may bank holiday rick steve recommend love',
 'select menu great price',
 'get angri want damn pho',
 'honeslti didnt tast fresh',
 'potato like rubber could tell made ahead time kept warmer',
 'fri great',
 'great touch',
 'servic prompt',
 'would not go back',
 'cashier care ever say still end wayyy overpr',
 'tri cape cod ravoli chicken cranberrymmmm',
 'disgust pretti sure human hair',
 'shock sign indic cash',
 'highli recommend',
 'waitress littl slow servic',
 'place not worth time let alon vega',
 'not like',
 'burritto blah',
 'food amaz',
 'servic also cute',
 'could care less interior beauti',
 'perform',
 'that rightth red velvet cakeohhh stuff good',
 'never brought salad ask',
 'hole wall great mexican street taco friendli staff',
 'took hour get food tabl restaur food luke warm sever run around like total overwhelm',
 'worst salmon sashimi',
 'also combo like burger fri beer decent deal',
 'like

In [17]:
# corpus=[]
# for i in df['Review']:
#     mystr=i.lower()  # lowercase
#     newstr=re.sub(r'[^A-Za-z\s]','',mystr) # remove special chracters/digit
#     list1=word_tokenize(newstr) # tokenization
#     list2=[ i for i in list1 if i not in s_list]  # stopwords removal
#     ps=PorterStemmer()
#     list3=[ ps.stem(i)  for i in list2]  # stemming
#     final=' '.join(list3)
#     corpus.append(final)


In [18]:
# vectorization >> convert text data into numeric form

# 1) countvectorizar  >> Count word
# 2) Tokenizer(keras)
# 3) TF-ID vectorizer


In [19]:
# 1) countvectorizar  >> Count word >> unique word new column

#                    Hi    how are  you good   by tc
# Hi how are you     1     1    1    1   0     0  0 
# are you good       0     0    1    1    1    0  0
# by by tc           0     0    0    0    0    2  1


In [20]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()
X=cv.fit_transform(corpus).toarray()
y=df['Liked']

In [21]:
X.shape

(1391, 1612)

In [22]:
# curse of dimensionality  >> model confuse 

In [23]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(1391, 1612))

In [24]:
cv.get_feature_names_out()

array(['absolut', 'absolutley', 'accid', ..., 'yum', 'yummi', 'zero'],
      shape=(1612,), dtype=object)

In [25]:
len(cv.get_feature_names_out())

1612

In [26]:
y

0       1
1       0
2       0
3       1
4       1
       ..
1386    0
1387    0
1388    0
1389    0
1390    0
Name: Liked, Length: 1391, dtype: int64

In [27]:
X_df=pd.DataFrame(X,columns=cv.get_feature_names_out())

In [28]:
X_df

,absolut,absolutley,accid,accommod,accomod,accordingli,account,ach,acknowledg,across,...,yelper,yet,youd,youll,your,yucki,yukon,yum,yummi,zero
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1386,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1387,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1388,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1389,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0


In [29]:
# cross Validation

In [30]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X_df,y,test_size=0.2,random_state=42)

In [31]:
# MODEL TRAINING
# Naive bays >> text data >> bayes therom >> cont ki probability count hoti hai
# >> CAlculate probabilyty of event
# multinomial >> text data

In [32]:
from sklearn.naive_bayes import MultinomialNB
clf= MultinomialNB()
clf.fit(X_train,y_train)


,alpha,1.0
,force_alpha,True
,fit_prior,True
,class_prior,None


In [33]:
clf.score(X_test,y_test)

0.8243727598566308

In [34]:
from sklearn.linear_model import LogisticRegression
clf1= LogisticRegression()
clf1.fit(X_train,y_train)


,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0
,fit_intercept,True
,intercept_scaling,1
,class_weight,None
,random_state,None
,solver,'lbfgs'
,max_iter,100
,multi_class,'deprecated'


In [35]:
clf1.score(X_test,y_test)

0.8172043010752689

In [36]:
# clf1 >> Logistic regression >> final

In [37]:
y_pred = clf1.predict(X_test)

In [38]:
from sklearn.metrics import confusion_matrix,classification_report

In [39]:
print(confusion_matrix(y_test,y_pred))

[[108  23]
 [ 28 120]]


In [40]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.79      0.82      0.81       131
           1       0.84      0.81      0.82       148

    accuracy                           0.82       279
   macro avg       0.82      0.82      0.82       279
weighted avg       0.82      0.82      0.82       279



In [41]:
# new review

In [42]:
a='good taste'

In [43]:
a= np.array(['bad taste'])

In [44]:
a_new=cv.transform(a).toarray()

In [45]:
a_new

array([[0, 0, 0, ..., 0, 0, 0]], shape=(1, 1612))

In [46]:
clf1.predict(a_new)

d:\desktop\RNN\lstm_env\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([0])

In [47]:
# solution >> RNN >> LSTM >> GRU
# next adv  >> transformer

In [48]:
# LSTM

In [49]:
# X=corpos
# y=df['liked']

In [50]:
df['Review']=corpus

In [51]:
df.head()

,Review,Liked
0,wow love place,1
1,crust not good,0
2,not tasti textur nasti,0
3,stop late may bank holiday rick steve recommen...,1
4,select menu great price,1


In [52]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [53]:
max_words = 5000
max_len = 100

In [54]:
tk= Tokenizer(num_words=max_words)
tk.fit_on_texts(df['Review'])

In [55]:
import pickle
with open('tokenizer.pkl','wb') as f:
    pickle.dump(tk,f)

In [56]:
X=tk.texts_to_sequences(df['Review'])

In [57]:
X = pad_sequences(X,maxlen=max_len)

In [58]:
X.shape

(1391, 100)

In [59]:
X
y=df['Liked']

In [60]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [61]:
# model training  >> LSTM

In [62]:
# Architecture of LSTM
# embedding layer
# LSTM layer
# Dropout layer(optional)
# Dense layer


In [63]:
# wow love place >> [123,516,78]
# LSTM cannot understand raw integers directly in a meaningful way.

# why embedding layer >> It converts each word ID into a dense vector representation.
#Captures semantic meaning meaning of words
#Similar words → similar vectors
# Learns during training



In [64]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout

In [65]:
model=Sequential()
model.add(Embedding(input_dim=max_words,output_dim=128))  # unit >> 128
model.add(LSTM(128, return_sequences=False))
model.add(Dropout(0.5))
model.add(Dense(1,activation='sigmoid'))

In [66]:
model.compile(
    loss='binary_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

In [67]:
history = model.fit(
    X_train,
    y_train,
    epochs=20,
    batch_size=32,
    validation_data=(X_test, y_test)

)                 

Epoch 1/20
35/35 ━━━━━━━━━━━━━━━━━━━━ 18s 213ms/step - accuracy: 0.5908 - loss: 0.6613 - val_accuracy: 0.6237 - val_loss: 0.6476
Epoch 2/20
35/35 ━━━━━━━━━━━━━━━━━━━━ 7s 203ms/step - accuracy: 0.7518 - loss: 0.5372 - val_accuracy: 0.7921 - val_loss: 0.4882
Epoch 3/20
35/35 ━━━━━━━━━━━━━━━━━━━━ 6s 179ms/step - accuracy: 0.9173 - loss: 0.2730 - val_accuracy: 0.8172 - val_loss: 0.4419
Epoch 4/20
35/35 ━━━━━━━━━━━━━━━━━━━━ 7s 203ms/step - accuracy: 0.9613 - loss: 0.1278 - val_accuracy: 0.7993 - val_loss: 0.5021
Epoch 5/20
35/35 ━━━━━━━━━━━━━━━━━━━━ 7s 192ms/step - accuracy: 0.9676 - loss: 0.1095 - val_accuracy: 0.8244 - val_loss: 0.4921
Epoch 6/20
35/35 ━━━━━━━━━━━━━━━━━━━━ 7s 183ms/step - accuracy: 0.9847 - loss: 0.0540 - val_accuracy: 0.8244 - val_loss: 0.5942
Epoch 7/20
35/35 ━━━━━━━━━━━━━━━━━━━━ 6s 179ms/step - accuracy: 0.9856 - loss: 0.0495 - val_accuracy: 0.8172 - val_loss: 0.6469
Epoch 8/20
35/35 ━━━━━━━━━━━━━━━━━━━━ 6s 179ms/step - accuracy: 0.9937 - loss: 0.0378 - val_accuracy: 0

In [68]:
loss, accuracy = model.evaluate(X_test,y_test)
print('Test Accuracy',accuracy)

9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 68ms/step - accuracy: 0.8315 - loss: 1.0661
Test Accuracy 0.8315412402153015


In [69]:
model.save('lstm_reviews.keras')

In [70]:
y_pred=model.predict(X_test)

9/9 ━━━━━━━━━━━━━━━━━━━━ 2s 125ms/step


In [71]:
y_pred1=[ 1 if i>0.5 else 0 for i in y_pred]

In [72]:
from sklearn.metrics import confusion_matrix,classification_report

In [73]:
print(confusion_matrix(y_test,y_pred1))

[[111  20]
 [ 27 121]]


In [74]:
print(classification_report(y_test,y_pred1))

              precision    recall  f1-score   support

           0       0.80      0.85      0.83       131
           1       0.86      0.82      0.84       148

    accuracy                           0.83       279
   macro avg       0.83      0.83      0.83       279
weighted avg       0.83      0.83      0.83       279



In [75]:
# new review

In [76]:
a= 'good taste'

In [77]:
def predict_text(text):
    text= text.lower()
    seq= tk.texts_to_sequences([text])
    padded = pad_sequences(seq,maxlen=max_len)
    pred=model.predict(padded)[0][0]

    if pred>0.5:
        return f"Positive({pred:.2f})"
    else:
        return f"Negative({pred:.2f})"
        

In [78]:
predict_text('not good taste')

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 171ms/step


'Negative(0.04)'

In [79]:
# not bad taste>> add i tsv file